name: build-documents

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/metanorma/metanorma-nist:latest
      credentials:
        username: metanorma-ci
        password: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Metanorma generate site
        id: build-and-publish
        uses: actions-mn/build-and-publish@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          agree-to-terms: true
          destination: none

      - name: Build NIST site on GitHub Pages
        run: |
          cp _config.yml _site/
          cp -a _includes _site/
          rm -f _site/index.html
          cp README.md _site/index.md

      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: site

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./_site
          publish_branch: nist-pages
          force_orphan: true
          enable_jekyll: true
          user_name: ${{ github.actor }}
          user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
          commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"

      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 0
